name: Compilar y Enviar Frontend React a Produccion (FTP)

on:
  push:
    branches:
      - dev
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código fuente (main - )
        uses: actions/checkout@v4
        